---
name: Continuous Integration

on:
  push:
    branches:
      - '**'
      - '!production'

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 14.x
          cache: yarn
      - run: echo "HOST=interflux.com" > .env
      - run: echo "LANGUAGE=en" >> .env
      - run: echo "PORT=4700" >> .env
      - run: yarn install --frozen-lockfile
      - run: yarn test
